# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PDz1G3qOPKZJ78VAr6gaSAcX8aQeXnWi
"""

from flask import Flask, request, jsonify
import joblib
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer

app = Flask(__name__)

# Load model and tokenizer
model = joblib.load('rnn_sentiment_model.pkl')
tokenizer = joblib.load('tokenizer.pkl')  # assume tokenizer also saved

# Settings (must match training)
MAX_LEN = 100

# Label map
label_map = {0: "Negative", 1: "Neutral", 2: "Positive"}

@app.route('/')
def home():
    return "RNN Sentiment Analysis API is running."

@app.route('/predict', methods=['POST'])
def predict():
    data = request.json
    if 'text' not in data:
        return jsonify({'error': 'No text provided'}), 400

    text = data['text']
    seq = tokenizer.texts_to_sequences([text])
    padded = pad_sequences(seq, maxlen=MAX_LEN)

    prediction = model.predict(padded)
    label = np.argmax(prediction, axis=1)[0]
    confidence = float(np.max(prediction))

    return jsonify({
        'prediction': label_map[label],
        'confidence': round(confidence, 3)
    })

if __name__ == '__main__':
    app.run(debug=True)